export const VIEWPORT_MARGIN_PX = 8;
export const INDICATOR_CLAMP_PADDING_PX = 4;
export const CURSOR_OFFSET_PX = 14;
export const OFFSCREEN_POSITION = -1000;

export const SELECTION_LERP_FACTOR = 0.95;

export const SUCCESS_LABEL_DURATION_MS = 1700;
export const PROGRESS_INDICATOR_DELAY_MS = 150;
export const SELECTION_CURSOR_SETTLE_DELAY_MS = 500;

export const DRAG_THRESHOLD_PX = 2;

export const AUTO_SCROLL_EDGE_THRESHOLD_PX = 25;
export const AUTO_SCROLL_SPEED_PX = 10;

export const Z_INDEX_CROSSHAIR = 2147483645;
export const Z_INDEX_SELECTION = 2147483646;
export const Z_INDEX_LABEL = 2147483647;

export const BRAND_COLOR_RGB = "210, 57, 192";
export const BRAND_COLOR_HEX = "#b21c8e";
